// Vendo.bio constraint: money flows AROUND us, never THROUGH us
// External links ONLY — no Stripe Checkout on landing pages.

import React from 'react';
import { CreatorProfile, GeneratedContent } from '../types';
import { Button } from './Button';

interface MediaKitProps {
  profile: CreatorProfile;
  content: GeneratedContent[];
}

export const MediaKit: React.FC<MediaKitProps> = ({ profile, content }) => {
  const totalClicks = profile.links.reduce((acc, l) => acc + l.clicks, 0);
  const approvedCount = content.filter(c => c.status === 'approved').length;

  return (
    <div className="max-w-4xl mx-auto px-6 py-12 bg-white min-h-screen">
      <div className="flex justify-between items-start mb-12 border-b border-slate-100 pb-8">
        <div className="flex items-center gap-6">
          <img src={profile.avatar} className="w-20 h-20 rounded-2xl shadow-lg" alt="Avatar" />
          <div>
            <h1 className="text-3xl font-bold text-slate-900">{profile.displayName}</h1>
            <p className="text-slate-500 font-medium">Digital Content Creator • @{profile.handle}</p>
          </div>
        </div>
        <Button onClick={() => window.print()} variant="outline">
          Download PDF
        </Button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
        <div className="bg-slate-50 p-6 rounded-2xl">
          <span className="text-slate-400 text-xs font-bold uppercase">Total reach</span>
          <div className="text-4xl font-bold text-indigo-600 mt-1">{(totalClicks / 10).toFixed(1)}k</div>
          <p className="text-xs text-slate-500 mt-2">Monthly Unique Impressions</p>
        </div>
        <div className="bg-slate-50 p-6 rounded-2xl">
          <span className="text-slate-400 text-xs font-bold uppercase">Engagement</span>
          <div className="text-4xl font-bold text-emerald-600 mt-1">12.4%</div>
          <p className="text-xs text-slate-500 mt-2">Conversion Through Rate</p>
        </div>
        <div className="bg-slate-50 p-6 rounded-2xl">
          <span className="text-slate-400 text-xs font-bold uppercase">Portfolio Size</span>
          <div className="text-4xl font-bold text-violet-600 mt-1">{approvedCount}</div>
          <p className="text-xs text-slate-500 mt-2">Verified AI Assets</p>
        </div>
      </div>

      <div className="space-y-12">
        <section>
          <h2 className="text-xl font-bold text-slate-900 mb-6 flex items-center gap-2">
            <span className="w-2 h-6 bg-indigo-600 rounded-full"></span>
            About the Creator
          </h2>
          <p className="text-slate-600 leading-relaxed text-lg italic">
            "{profile.bio} Expertly blending human creativity with state-of-the-art AI generation to produce high-impact commercial visuals."
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-slate-900 mb-6 flex items-center gap-2">
            <span className="w-2 h-6 bg-emerald-600 rounded-full"></span>
            Featured Content
          </h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {content.filter(c => c.status === 'approved').slice(0, 4).map(item => (
              <div key={item.id} className="aspect-[3/4] rounded-xl overflow-hidden border border-slate-100 shadow-sm">
                <img src={item.hero_url} className="w-full h-full object-cover" alt="Portfolio item" />
              </div>
            ))}
          </div>
        </section>
      </div>

      <div className="mt-20 pt-8 border-t border-slate-100 text-center text-slate-400 text-xs">
        Media Kit generated by AdGenius AI • {new Date().toLocaleDateString()}
      </div>
    </div>
  );
};